remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "neon"   # options: default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

title: APSC 160 — Final Exam Practice
description: Self-study practice problems

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-include-cache

search: true