remote_theme: jeffreytse/jekyll-theme-yat

title: APSC 160 — Final Exam Practice
author: Isaac
description: Self-study practice problems

yat:
  skin: dark          # or "light"
  highlight_theme: monokai   # great for code blocks

plugins:
  - jekyll-remote-theme
  - jekyll-feed